package hello.model.ddb;


import javax.persistence.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PhotoInfo")
public class PhotoInfo {

	private String id;
	private String bucket;
	private String prefix;
	private String text;
	private String translated;
	    
	public PhotoInfo() {
	}
	    
	public PhotoInfo(String bucket, String prefix, String text, String translated) {
	this.prefix = prefix;
	this.bucket = bucket;
	this.text = text;
	this.translated = translated;
	}
 
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	 
	@DynamoDBAttribute
	public String getPrefix() {
		return prefix;
	}
	
	@DynamoDBAttribute
	public String getBucket() {
		return bucket;
	}
	
	@DynamoDBAttribute	
	public String getText() {
		return text;
	}
	
	@DynamoDBAttribute	
	public String getTranslated() {
		return translated;
	}

  	public void setBucket(String bucket) {
  		this.bucket = bucket;
  	}

  	public void setText(String text) {
  		this.text = text;
  	}


  	public void setTanslated(String translated) {
  		this.translated = translated;
  	}
		
  @Override
  public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      PhotoInfo p = (PhotoInfo) o;

      return id.equals(p.id);
  }

  @Override
  public int hashCode() {
      return id.hashCode();
  }
}
