AWSTemplateFormatVersion: '2010-09-09'
Description: RESTful API backed by AI and DynamoDB
Globals:
  Api:
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''*'''
  Function:
    Runtime: java8
Resources:
  TranslateFunction:
    Properties:
      CodeUri: s3://seon-virginia-01/bb00b47d358c5a26340c34523af250dc
      Environment:
        Variables:
          S3_BUCKET: s3://seon-virginia-01
      Events:
        PostResource:
          Properties:
            Method: post
            Path: /translate/do
          Type: Api
      FunctionName: workshop-translate-01
      Handler: com.amazonaws.lambda.LambdaTranslateHandler::handleRequest
      MemorySize: 1024
      Policies: TranslateReadOnly
      Runtime: java8
      Tags:
        ContactTag: workshop-translte
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
